pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = "https://nexus.inductiveautomation.com/repository/public"
        }
    }
}

rootProject.name = "ignition-git-module"

dependencyResolutionManagement {
    repositories {
        maven {
            url "https://nexus.inductiveautomation.com/repository/public"
        }
        mavenCentral()

        // Node.js download repository for the web-ui subproject's node-gradle plugin.
        ivy {
            name = "Node.js"
            setUrl("https://nodejs.org/dist/")
            patternLayout {
                artifact("v[revision]/[artifact](-v[revision]-[classifier]).[ext]")
            }
            metadataSources {
                artifact()
            }
            content {
                includeModule("org.nodejs", "node")
            }
        }
    }
}

include(
    ":",
    ":common",
    ":designer",
    ":gateway",
    ":web-ui"
)
