Actions.Push.ConfirmMessage=Everything went well during the Push.

Actions.Pull.ConfirmMessage=Everything went well during the Pull.

Actions.Commit.ConfirmMessage=Everything went well during the Commit.

Actions.Branch.CheckoutConfirmMessage=Branch checkout completed successfully.

Actions.Fetch.ConfirmMessage=Fetch completed successfully.

Commit.Title=Commit

History.Title=History
